[2024-11-18T17:49:51.979+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-18T17:49:52.138+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.spark_job scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-18T17:49:52.165+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.spark_job scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-18T17:49:52.167+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-18T17:49:52.451+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2024-11-04 00:00:00+00:00
[2024-11-18T17:49:52.598+0000] {standard_task_runner.py:64} INFO - Started process 1752 to run task
[2024-11-18T17:49:52.637+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'spark_job', 'scheduled__2024-11-04T00:00:00+00:00', '--job-id', '665', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmpzb7qms93']
[2024-11-18T17:49:52.653+0000] {standard_task_runner.py:91} INFO - Job 665: Subtask spark_job
[2024-11-18T17:49:52.984+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_dag.spark_job scheduled__2024-11-04T00:00:00+00:00 [running]> on host 3fa30a842a1c
[2024-11-18T17:49:53.393+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T00:00:00+00:00'
[2024-11-18T17:49:53.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-18T17:49:53.450+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-11-18T17:49:53.467+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py
[2024-11-18T17:50:22.284+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-18T17:50:22.572+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:51:03.439+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SparkContext: Running Spark version 3.5.3
[2024-11-18T17:51:03.695+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-11-18T17:51:03.730+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SparkContext: Java version 17.0.12
[2024-11-18T17:51:04.093+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-18T17:51:05.669+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:05 INFO ResourceUtils: ==============================================================
[2024-11-18T17:51:05.672+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:05 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-18T17:51:05.731+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:05 INFO ResourceUtils: ==============================================================
[2024-11-18T17:51:05.734+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:05 INFO SparkContext: Submitted application: Airflow Spark Job
[2024-11-18T17:51:06.112+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-18T17:51:06.186+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO ResourceProfile: Limiting resource is cpu
[2024-11-18T17:51:06.188+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-18T17:51:06.340+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO SecurityManager: Changing view acls to: ***
[2024-11-18T17:51:06.341+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO SecurityManager: Changing modify acls to: ***
[2024-11-18T17:51:06.346+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO SecurityManager: Changing view acls groups to:
[2024-11-18T17:51:06.347+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO SecurityManager: Changing modify acls groups to:
[2024-11-18T17:51:06.388+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-11-18T17:51:08.908+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO Utils: Successfully started service 'sparkDriver' on port 41251.
[2024-11-18T17:51:15.515+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:15 INFO SparkEnv: Registering MapOutputTracker
[2024-11-18T17:51:16.563+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:16 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-18T17:51:17.315+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:17 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-18T17:51:17.365+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:17 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-18T17:51:17.540+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:17 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-18T17:51:17.766+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:17 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-3ba4b1a0-0855-4bf0-a4d5-e3eb3fa14649
[2024-11-18T17:51:17.872+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:17 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-18T17:51:18.009+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:17 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-18T17:51:21.147+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-18T17:51:21.856+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-11-18T17:51:21.866+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-11-18T17:51:21.875+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-11-18T17:51:21.877+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-11-18T17:51:21.884+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-11-18T17:51:21.888+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-11-18T17:51:21.902+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2024-11-18T17:51:21.932+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2024-11-18T17:51:21.955+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2024-11-18T17:51:22.047+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:22 INFO Utils: Successfully started service 'SparkUI' on port 4049.
[2024-11-18T17:51:23.485+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:23 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:51:27.056+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:27 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:51:27.058+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:51:27.058+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:51:27.059+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:51:27.059+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:51:27.060+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:51:27.060+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:51:27.060+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:51:27.061+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:51:27.061+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:51:27.062+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:51:27.062+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:51:27.063+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:27.064+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/172.19.0.4:7077
[2024-11-18T17:51:27.064+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:51:27.064+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:51:27.065+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:51:27.065+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:51:27.065+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:51:27.065+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:51:27.065+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:51:27.066+0000] {spark_submit.py:634} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark/172.19.0.4:7077
[2024-11-18T17:51:27.066+0000] {spark_submit.py:634} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-18T17:51:27.066+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-11-18T17:51:27.067+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-11-18T17:51:27.067+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-11-18T17:51:27.067+0000] {spark_submit.py:634} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-18T17:51:27.068+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-18T17:51:27.068+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-18T17:51:27.068+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-18T17:51:27.068+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-18T17:51:27.069+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-18T17:51:27.069+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:51:27.069+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:51:27.069+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:51:27.070+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:43.504+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:43 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:51:43.513+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:43 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:51:43.514+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:51:43.514+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:51:43.515+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:51:43.515+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:51:43.516+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:51:43.516+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:51:43.516+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:51:43.517+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:51:43.517+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:51:43.517+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:51:43.517+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:51:43.518+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:43.518+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/172.19.0.4:7077
[2024-11-18T17:51:43.518+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:51:43.519+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:51:43.519+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:51:43.519+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:51:43.519+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:51:43.519+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:51:43.520+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:51:43.520+0000] {spark_submit.py:634} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark/172.19.0.4:7077
[2024-11-18T17:51:43.520+0000] {spark_submit.py:634} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-18T17:51:43.520+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-11-18T17:51:43.521+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-11-18T17:51:43.521+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-11-18T17:51:43.521+0000] {spark_submit.py:634} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-18T17:51:43.522+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-18T17:51:43.522+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-18T17:51:43.522+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-18T17:51:43.523+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-18T17:51:43.523+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-18T17:51:43.524+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:51:43.524+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:51:43.524+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:51:43.524+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:52:03.507+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:03 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:52:03.538+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:03 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.8:7077 after 15 ms (0 ms spent in bootstraps)
[2024-11-18T17:52:04.303+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241118175204-0005
[2024-11-18T17:52:04.369+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 43899.
[2024-11-18T17:52:04.370+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO NettyBlockTransferService: Server created on 3fa30a842a1c:43899
[2024-11-18T17:52:04.378+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-18T17:52:04.450+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 3fa30a842a1c, 43899, None)
[2024-11-18T17:52:04.470+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMasterEndpoint: Registering block manager 3fa30a842a1c:43899 with 434.4 MiB RAM, BlockManagerId(driver, 3fa30a842a1c, 43899, None)
[2024-11-18T17:52:04.488+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 3fa30a842a1c, 43899, None)
[2024-11-18T17:52:04.491+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 3fa30a842a1c, 43899, None)
[2024-11-18T17:52:56.217+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:53:35.086+0000] {spark_submit.py:634} INFO - 24/11/18 17:53:35 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener HeartbeatReceiver took 50.596365856s.
[2024-11-18T17:53:35.098+0000] {spark_submit.py:634} INFO - 24/11/18 17:53:35 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener AppStatusListener took 50.890946932s.
[2024-11-18T17:53:35.429+0000] {spark_submit.py:634} INFO - 24/11/18 17:53:35 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-18T17:53:59.522+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:54:41.737+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:40 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@17297561)) by listener AppStatusListener took 1.437248368s.
[2024-11-18T17:54:45.982+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:44 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@53b2cf1e)) by listener AppStatusListener took 1.031539639s.
[2024-11-18T17:54:48.514+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:48 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-11-18T17:54:48.843+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:48 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2024-11-18T17:55:14.042+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO CodeGenerator: Code generated in 1815.288342 ms
[2024-11-18T17:55:14.278+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO SparkContext: Starting job: showString at NativeMethodAccessorImpl.java:0
[2024-11-18T17:55:14.316+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Got job 0 (showString at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-11-18T17:55:14.318+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Final stage: ResultStage 0 (showString at NativeMethodAccessorImpl.java:0)
[2024-11-18T17:55:14.320+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Parents of final stage: List()
[2024-11-18T17:55:14.328+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Missing parents: List()
[2024-11-18T17:55:14.363+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-11-18T17:55:14.731+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 13.1 KiB, free 434.4 MiB)
[2024-11-18T17:55:14.899+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 6.8 KiB, free 434.4 MiB)
[2024-11-18T17:55:14.912+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 3fa30a842a1c:43899 (size: 6.8 KiB, free: 434.4 MiB)
[2024-11-18T17:55:14.922+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2024-11-18T17:55:14.969+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-11-18T17:55:14.978+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2024-11-18T17:55:30.020+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:30 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-11-18T17:55:45.004+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:45 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-11-18T17:55:46.498+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:46 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241118175204-0005/0 on worker-20241118175528-172.19.0.10-35337 (172.19.0.10:35337) with 1 core(s)
[2024-11-18T17:55:46.503+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:46 INFO StandaloneSchedulerBackend: Granted executor ID app-20241118175204-0005/0 on hostPort 172.19.0.10:35337 with 1 core(s), 1024.0 MiB RAM
[2024-11-18T17:55:46.504+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:46 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241118175204-0005/1 on worker-20241118175528-172.19.0.6-33793 (172.19.0.6:33793) with 1 core(s)
[2024-11-18T17:55:46.504+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:46 INFO StandaloneSchedulerBackend: Granted executor ID app-20241118175204-0005/1 on hostPort 172.19.0.6:33793 with 1 core(s), 1024.0 MiB RAM
[2024-11-18T17:55:46.531+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:46 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241118175204-0005/0 is now RUNNING
[2024-11-18T17:55:46.532+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:46 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241118175204-0005/1 is now RUNNING
[2024-11-18T17:55:49.309+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.6:51968) with ID 1,  ResourceProfileId 0
[2024-11-18T17:55:49.326+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.10:38512) with ID 0,  ResourceProfileId 0
[2024-11-18T17:55:49.428+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.6:37835 with 434.4 MiB RAM, BlockManagerId(1, 172.19.0.6, 37835, None)
[2024-11-18T17:55:49.431+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.10:39423 with 434.4 MiB RAM, BlockManagerId(0, 172.19.0.10, 39423, None)
[2024-11-18T17:55:49.519+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.19.0.10, executor 0, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:55:49.628+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.19.0.10 executor 0): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:49.629+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:49.630+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.630+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.631+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.631+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.631+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:49.631+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:49.632+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:49.632+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:49.632+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:49.632+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:49.633+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:49.633+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:49.633+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:49.634+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:49.634+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:49.636+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.19.0.10, executor 0, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:55:49.663+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on 172.19.0.10, executor 0: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 1]
[2024-11-18T17:55:49.665+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.19.0.6, executor 1, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:55:49.757+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) on 172.19.0.6, executor 1: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 2]
[2024-11-18T17:55:49.759+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.19.0.6, executor 1, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:55:49.775+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) on 172.19.0.6, executor 1: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 3]
[2024-11-18T17:55:49.779+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2024-11-18T17:55:49.783+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2024-11-18T17:55:49.787+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSchedulerImpl: Cancelling stage 0
[2024-11-18T17:55:49.788+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 1): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:49.789+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:49.790+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.790+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.791+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.791+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.791+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:49.792+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:49.792+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:49.792+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:49.793+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:49.793+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:49.793+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:49.794+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:49.795+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:49.795+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:49.795+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:49.796+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:55:49.796+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO DAGScheduler: ResultStage 0 (showString at NativeMethodAccessorImpl.java:0) failed in 35.351 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 1): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:49.797+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:49.797+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.797+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.798+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.798+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.798+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:49.798+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:49.799+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:49.799+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:49.800+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:49.800+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:49.800+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:49.801+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:49.801+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:49.801+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:49.801+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:49.802+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:55:49.802+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:49 INFO DAGScheduler: Job 0 failed: showString at NativeMethodAccessorImpl.java:0, took 35.515544 s
[2024-11-18T17:55:49.970+0000] {spark_submit.py:634} INFO - Traceback (most recent call last):
[2024-11-18T17:55:49.971+0000] {spark_submit.py:634} INFO - File "/opt/***/dags/spark_job.py", line 16, in <module>
[2024-11-18T17:55:49.972+0000] {spark_submit.py:634} INFO - df.show()
[2024-11-18T17:55:49.973+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 947, in show
[2024-11-18T17:55:49.974+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 965, in _show_string
[2024-11-18T17:55:49.975+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-11-18T17:55:49.975+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-11-18T17:55:49.976+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-11-18T17:55:49.977+0000] {spark_submit.py:634} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o41.showString.
[2024-11-18T17:55:49.977+0000] {spark_submit.py:634} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 1): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:49.978+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:49.978+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.978+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.978+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.979+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.979+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:49.979+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:49.980+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:49.980+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:49.980+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:49.981+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:49.981+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:49.981+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:49.981+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:49.981+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:49.982+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:49.982+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:55:49.982+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2024-11-18T17:55:49.982+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2024-11-18T17:55:49.982+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2024-11-18T17:55:49.983+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2024-11-18T17:55:49.983+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2024-11-18T17:55:49.983+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2024-11-18T17:55:49.983+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2024-11-18T17:55:49.983+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2024-11-18T17:55:49.984+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2024-11-18T17:55:49.984+0000] {spark_submit.py:634} INFO - at scala.Option.foreach(Option.scala:407)
[2024-11-18T17:55:49.984+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2024-11-18T17:55:49.985+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2024-11-18T17:55:49.985+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2024-11-18T17:55:49.985+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2024-11-18T17:55:49.985+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2024-11-18T17:55:49.986+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2024-11-18T17:55:49.986+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2024-11-18T17:55:49.986+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2024-11-18T17:55:49.987+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2024-11-18T17:55:49.987+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:530)
[2024-11-18T17:55:49.987+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:483)
[2024-11-18T17:55:49.987+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:61)
[2024-11-18T17:55:49.987+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:4333)
[2024-11-18T17:55:49.988+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:3316)
[2024-11-18T17:55:49.988+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4323)
[2024-11-18T17:55:49.988+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
[2024-11-18T17:55:49.988+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4321)
[2024-11-18T17:55:49.988+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2024-11-18T17:55:49.989+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2024-11-18T17:55:49.989+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2024-11-18T17:55:49.989+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2024-11-18T17:55:49.990+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2024-11-18T17:55:49.990+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4321)
[2024-11-18T17:55:49.990+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.head(Dataset.scala:3316)
[2024-11-18T17:55:49.990+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.take(Dataset.scala:3539)
[2024-11-18T17:55:49.991+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.getRows(Dataset.scala:280)
[2024-11-18T17:55:49.991+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.showString(Dataset.scala:315)
[2024-11-18T17:55:49.991+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-18T17:55:49.991+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-11-18T17:55:49.992+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-18T17:55:49.992+0000] {spark_submit.py:634} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-11-18T17:55:49.992+0000] {spark_submit.py:634} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-18T17:55:49.992+0000] {spark_submit.py:634} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-18T17:55:49.993+0000] {spark_submit.py:634} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-18T17:55:49.993+0000] {spark_submit.py:634} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-18T17:55:49.993+0000] {spark_submit.py:634} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-18T17:55:49.994+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-18T17:55:49.994+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-18T17:55:49.994+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:49.994+0000] {spark_submit.py:634} INFO - Caused by: java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:49.995+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:49.995+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.995+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.996+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:49.996+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:49.996+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:49.996+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:49.997+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:49.997+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:49.997+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:49.997+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:49.997+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:49.998+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:49.998+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:49.998+0000] {spark_submit.py:634} INFO - ... 1 more
[2024-11-18T17:55:49.998+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:50.521+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO SparkContext: Invoking stop() from shutdown hook
[2024-11-18T17:55:50.521+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-18T17:55:50.529+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO SparkUI: Stopped Spark web UI at http://3fa30a842a1c:4049
[2024-11-18T17:55:50.532+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-11-18T17:55:50.533+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-11-18T17:55:50.567+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-11-18T17:55:50.621+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO MemoryStore: MemoryStore cleared
[2024-11-18T17:55:50.622+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO BlockManager: BlockManager stopped
[2024-11-18T17:55:50.628+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-11-18T17:55:50.631+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-11-18T17:55:50.649+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO SparkContext: Successfully stopped SparkContext
[2024-11-18T17:55:50.651+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO ShutdownHookManager: Shutdown hook called
[2024-11-18T17:55:50.654+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-8a735ca5-fe4f-4bd1-8ca6-a07a9395e0f4
[2024-11-18T17:55:50.662+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-4e711731-4e3c-4b99-bc90-13a6784b1df2/pyspark-5e271e38-d50b-44d5-aeb9-7fc782ecc13a
[2024-11-18T17:55:50.670+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-4e711731-4e3c-4b99-bc90-13a6784b1df2
[2024-11-18T17:55:50.758+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-18T17:55:50.819+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.
[2024-11-18T17:55:50.861+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=spark_job, run_id=scheduled__2024-11-04T00:00:00+00:00, execution_date=20241104T000000, start_date=20241118T174952, end_date=20241118T175550
[2024-11-18T17:55:50.981+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 665 for task spark_job (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.; 1752)
[2024-11-18T17:55:51.030+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-18T17:55:51.119+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T17:55:51.121+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
