[2024-11-18T17:37:55.743+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-18T17:37:55.778+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.spark_task scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-11-18T17:37:55.789+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.spark_task scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-11-18T17:37:55.790+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-11-18T17:37:55.817+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_task> on 2024-05-04 00:00:00+00:00
[2024-11-18T17:37:55.853+0000] {standard_task_runner.py:64} INFO - Started process 149 to run task
[2024-11-18T17:37:55.878+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'spark_task', 'scheduled__2024-05-04T00:00:00+00:00', '--job-id', '620', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmpgp1cs0mx']
[2024-11-18T17:37:55.896+0000] {standard_task_runner.py:91} INFO - Job 620: Subtask spark_task
[2024-11-18T17:37:56.074+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_dag.spark_task scheduled__2024-05-04T00:00:00+00:00 [running]> on host 39153155bde1
[2024-11-18T17:37:56.417+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='spark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T00:00:00+00:00'
[2024-11-18T17:37:56.435+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-18T17:37:56.469+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-11-18T17:37:56.476+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py
[2024-11-18T17:38:29.947+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:29 INFO SparkContext: Running Spark version 3.5.3
[2024-11-18T17:38:29.963+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:29 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-11-18T17:38:29.967+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:29 INFO SparkContext: Java version 17.0.12
[2024-11-18T17:38:31.174+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-18T17:38:31.901+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO ResourceUtils: ==============================================================
[2024-11-18T17:38:31.910+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-18T17:38:31.918+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO ResourceUtils: ==============================================================
[2024-11-18T17:38:31.942+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:31 INFO SparkContext: Submitted application: Airflow Spark Job
[2024-11-18T17:38:32.380+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-18T17:38:32.578+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO ResourceProfile: Limiting resource is cpu
[2024-11-18T17:38:32.589+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:32 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-18T17:38:33.268+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:33 INFO SecurityManager: Changing view acls to: ***
[2024-11-18T17:38:33.276+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:33 INFO SecurityManager: Changing modify acls to: ***
[2024-11-18T17:38:33.291+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:33 INFO SecurityManager: Changing view acls groups to:
[2024-11-18T17:38:33.310+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:33 INFO SecurityManager: Changing modify acls groups to:
[2024-11-18T17:38:33.343+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:33 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-11-18T17:38:39.325+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:39 INFO Utils: Successfully started service 'sparkDriver' on port 46377.
[2024-11-18T17:38:40.212+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:40 INFO SparkEnv: Registering MapOutputTracker
[2024-11-18T17:38:41.146+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:41 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-18T17:38:41.470+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:41 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-18T17:38:41.534+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:41 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-18T17:38:41.568+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:41 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-18T17:38:46.437+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:46 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-72830997-a55a-4566-aae3-6fa035c33d37
[2024-11-18T17:38:49.270+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:49 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-18T17:38:50.722+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:50 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-18T17:38:58.458+0000] {spark_submit.py:634} INFO - 24/11/18 17:38:58 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-18T17:39:14.763+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-11-18T17:39:14.809+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-11-18T17:39:14.824+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-11-18T17:39:14.832+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-11-18T17:39:14.837+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-11-18T17:39:14.910+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-11-18T17:39:14.912+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2024-11-18T17:39:14.927+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:14 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2024-11-18T17:39:15.214+0000] {spark_submit.py:634} INFO - 24/11/18 17:39:15 INFO Utils: Successfully started service 'SparkUI' on port 4048.
[2024-11-18T17:39:25.374+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-18T17:40:33.174+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:40:35.464+0000] {spark_submit.py:634} INFO - 24/11/18 17:40:35 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:41:06.364+0000] {spark_submit.py:634} INFO - 24/11/18 17:41:05 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:41:10.976+0000] {spark_submit.py:634} INFO - 24/11/18 17:41:10 WARN TransportClientFactory: DNS resolution failed for spark/<unresolved>:7077 took 15640 ms
[2024-11-18T17:41:21.136+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:41:22.116+0000] {spark_submit.py:634} INFO - 24/11/18 17:41:21 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:41:42.412+0000] {spark_submit.py:634} INFO - 24/11/18 17:41:42 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-11-18T17:41:44.539+0000] {spark_submit.py:634} INFO - 24/11/18 17:41:42 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-11-18T17:42:01.042+0000] {spark_submit.py:634} INFO - 24/11/18 17:41:45 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:42:01.174+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:42:01.297+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:42:01.905+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:42:03.772+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:42:06.344+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:42:09.606+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:42:14.866+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:42:14.925+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:42:14.928+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:42:14.934+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:42:14.949+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:42:14.953+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:42:14.959+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:42:14.961+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/<unresolved>:7077
[2024-11-18T17:42:14.975+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:42:14.995+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:42:15.006+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:42:15.012+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:42:15.024+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:42:15.030+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:42:15.052+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:42:15.054+0000] {spark_submit.py:634} INFO - Caused by: java.net.UnknownHostException: spark: Temporary failure in name resolution
[2024-11-18T17:42:15.057+0000] {spark_submit.py:634} INFO - at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[2024-11-18T17:42:15.060+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
[2024-11-18T17:42:15.063+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
[2024-11-18T17:42:15.114+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
[2024-11-18T17:42:15.119+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
[2024-11-18T17:42:15.125+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
[2024-11-18T17:42:15.135+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
[2024-11-18T17:42:15.142+0000] {spark_submit.py:634} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1256)
[2024-11-18T17:42:15.149+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2024-11-18T17:42:15.150+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2024-11-18T17:42:15.154+0000] {spark_submit.py:634} INFO - at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[2024-11-18T17:42:15.165+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2024-11-18T17:42:15.185+0000] {spark_submit.py:634} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2024-11-18T17:42:15.189+0000] {spark_submit.py:634} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2024-11-18T17:42:15.190+0000] {spark_submit.py:634} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2024-11-18T17:42:15.198+0000] {spark_submit.py:634} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2024-11-18T17:42:15.202+0000] {spark_submit.py:634} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2024-11-18T17:42:15.205+0000] {spark_submit.py:634} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2024-11-18T17:42:15.207+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:220)
[2024-11-18T17:42:15.208+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2024-11-18T17:42:15.209+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:189)
[2024-11-18T17:42:15.211+0000] {spark_submit.py:634} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:175)
[2024-11-18T17:42:15.214+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[2024-11-18T17:42:15.216+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
[2024-11-18T17:42:15.227+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[2024-11-18T17:42:15.230+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
[2024-11-18T17:42:15.231+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
[2024-11-18T17:42:15.237+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
[2024-11-18T17:42:15.240+0000] {spark_submit.py:634} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2024-11-18T17:42:15.252+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
[2024-11-18T17:42:15.269+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2024-11-18T17:42:15.306+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2024-11-18T17:42:15.308+0000] {spark_submit.py:634} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2024-11-18T17:42:15.312+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[2024-11-18T17:42:15.315+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[2024-11-18T17:42:15.387+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[2024-11-18T17:42:15.428+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[2024-11-18T17:42:15.450+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:42:15.451+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:42:15.452+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:42:15.453+0000] {spark_submit.py:634} INFO - ... 1 more
[2024-11-18T17:42:15.456+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:15 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35505.
[2024-11-18T17:42:15.467+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:15 INFO NettyBlockTransferService: Server created on 39153155bde1:35505
[2024-11-18T17:42:15.631+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:15 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-18T17:42:16.840+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:16 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 39153155bde1, 35505, None)
[2024-11-18T17:42:16.881+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:16 INFO BlockManagerMasterEndpoint: Registering block manager 39153155bde1:35505 with 434.4 MiB RAM, BlockManagerId(driver, 39153155bde1, 35505, None)
[2024-11-18T17:42:16.959+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:16 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 39153155bde1, 35505, None)
[2024-11-18T17:42:16.965+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:16 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 39153155bde1, 35505, None)
[2024-11-18T17:42:24.570+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:24 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-18T17:42:30.232+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-18T17:42:30.468+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO SparkUI: Stopped Spark web UI at http://39153155bde1:4048
[2024-11-18T17:42:30.509+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-11-18T17:42:30.517+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-11-18T17:42:30.601+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2024-11-18T17:42:30.646+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-11-18T17:42:30.808+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO MemoryStore: MemoryStore cleared
[2024-11-18T17:42:30.811+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO BlockManager: BlockManager stopped
[2024-11-18T17:42:30.822+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-11-18T17:42:30.824+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:30 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-11-18T17:42:31.093+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:31 INFO SparkContext: Successfully stopped SparkContext
[2024-11-18T17:42:32.733+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:32 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-11-18T17:42:32.811+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:32 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2024-11-18T17:42:33.039+0000] {spark_submit.py:634} INFO - Traceback (most recent call last):
[2024-11-18T17:42:33.041+0000] {spark_submit.py:634} INFO - File "/opt/***/dags/spark_job.py", line 14, in <module>
[2024-11-18T17:42:33.053+0000] {spark_submit.py:634} INFO - df = spark.createDataFrame(data, ["Name", "Application Type", "Use Count"])
[2024-11-18T17:42:33.054+0000] {spark_submit.py:634} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-18T17:42:33.056+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1443, in createDataFrame
[2024-11-18T17:42:33.057+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1485, in _create_dataframe
[2024-11-18T17:42:33.058+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 1093, in _createFromLocal
[2024-11-18T17:42:33.061+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 952, in _inferSchemaFromList
[2024-11-18T17:42:33.064+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 624, in _jconf
[2024-11-18T17:42:33.068+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-11-18T17:42:33.070+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-11-18T17:42:33.077+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-11-18T17:42:33.078+0000] {spark_submit.py:634} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o23.sessionState.
[2024-11-18T17:42:33.081+0000] {spark_submit.py:634} INFO - : java.lang.IllegalStateException: LiveListenerBus is stopped.
[2024-11-18T17:42:33.082+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.LiveListenerBus.addToQueue(LiveListenerBus.scala:92)
[2024-11-18T17:42:33.083+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.LiveListenerBus.addToStatusQueue(LiveListenerBus.scala:75)
[2024-11-18T17:42:33.083+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:115)
[2024-11-18T17:42:33.084+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.$anonfun$sharedState$1(SparkSession.scala:143)
[2024-11-18T17:42:33.084+0000] {spark_submit.py:634} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-11-18T17:42:33.084+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:143)
[2024-11-18T17:42:33.085+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:142)
[2024-11-18T17:42:33.086+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:162)
[2024-11-18T17:42:33.088+0000] {spark_submit.py:634} INFO - at scala.Option.getOrElse(Option.scala:189)
[2024-11-18T17:42:33.089+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:160)
[2024-11-18T17:42:33.091+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:157)
[2024-11-18T17:42:33.093+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-18T17:42:33.094+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-11-18T17:42:33.098+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-18T17:42:33.100+0000] {spark_submit.py:634} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-11-18T17:42:33.101+0000] {spark_submit.py:634} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-18T17:42:33.106+0000] {spark_submit.py:634} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-18T17:42:33.108+0000] {spark_submit.py:634} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-18T17:42:33.116+0000] {spark_submit.py:634} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-18T17:42:33.117+0000] {spark_submit.py:634} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-18T17:42:33.118+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-18T17:42:33.119+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-18T17:42:33.121+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:42:33.122+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:42:33.868+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:33 INFO ShutdownHookManager: Shutdown hook called
[2024-11-18T17:42:33.886+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-980ebe69-49c5-4ea9-abe7-7e2f9419afff/pyspark-fdf0011a-17c2-414b-8f21-7466eec20d3e
[2024-11-18T17:42:33.928+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-980ebe69-49c5-4ea9-abe7-7e2f9419afff
[2024-11-18T17:42:33.954+0000] {spark_submit.py:634} INFO - 24/11/18 17:42:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-91ffb768-fadc-41b6-9935-c95771ad1b44
[2024-11-18T17:42:34.072+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-18T17:42:34.154+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.
[2024-11-18T17:42:34.180+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_dag, task_id=spark_task, run_id=scheduled__2024-05-04T00:00:00+00:00, execution_date=20240504T000000, start_date=20241118T173755, end_date=20241118T174234
[2024-11-18T17:42:34.262+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 620 for task spark_task (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.; 149)
[2024-11-18T17:42:34.331+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-18T17:42:34.391+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T17:42:34.406+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
